### ISSUE TITLE
TML will be a decidable language that holds unique characteristics to interpret and redefine itself

### ISSUE THREAD

**Issue by logicmoo** [IDNI/TML#25]
TML will be a decidable language that holds unique characteristics to interpret and redefine itself. 

We know that Datalog can theoretically be coded in datalog just no one has tried yet.

Anyways thus TML can theoretically be coded in TML. 

This issue is a "feature reminder" that it would be nice to have a test example to verify when this begins to happen.

**Comment by naturalog** [comment]
The ability to be decidable and self-define at the same time, is more accurately described as "rare" rather "unique". Indeed Datalog got such abilities, and a paper by Imhof shows two different proofs for that (for both Datalog and TML, namely LFP and PFP).

I'm not aware of an implementation of a Datalog self interpreter, and I don't have an algorithm to implement TML self-interpreter, at least not a "full" self-interpreter. But, we don't need to write a self interpreter at all, and the theoretical result of the theoretical ability to self interpret, tells us that we can add a quoting operator to the langugae without breaking the logic. And indeed a quoting/unquoting operator is planned to be supported in the future.

**Comment by logicmoo** [comment]
Is there going to be support for letting TML redefine parts of itself?  In ways in which it can improve itself?

**Comment by naturalog** [comment]
closed due to irrelevance and nonsense
