### ISSUE TITLE
QUESTION: Will users of TML be allowed to make use of logical negation? (specifically Modus Tollens deduction)

### ISSUE THREAD

**Issue by logicmoo** [IDNI/TML#31]
TML currently only has deletion and negation by failure.  Ohad over and over said it had logical negation as well ..but I am unable to see how this could be true.  Here is example:
````
human(X)=>mortal(X).
~mortal(joe).
````

Therefore

````
! ~human(joe).  
````
should be true

Does TML have logical negation?  Can it be tested somehow?

If not, will users of TML be allowed to make use of logical negation? (specifically Modus Tollens deduction like above)

**Comment by naturalog** [comment]
closed due to nonsense
